#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso src/eigenSolver
wclean libso src/quadratureMethods/univariateMomentSet
wclean libso src/quadratureMethods/extentedMomentInversion
wclean libso src/quadratureMethods/quadratureApproximation
wclean libso src/quadratureMethods/populationBalanceModels
wclean libso crystallization
wclean 

# ----------------------------------------------------------------- end-of-file
