#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

blockMesh
cp 0/alpha.sludge.orig 0/alpha.sludge
$(getApplication) > log 

#------------------------------------------------------------------------------
