#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name

blockMesh
snappyHexMesh -overwrite
rm -rf 0
cp -r 0.org 0


explosiveSonicFoam > log 

#decomposePar

#mpirun -np 4 explosiveSonicFoam -parallel > log 

#reconstructPar

#------------------------------------------------------------------------------
