#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

blockMesh
topoSet

cp 0/alpha.water.org 0/alpha.water
cp 0/T.org 0/T
cp 0/U.org 0/U

splitMeshRegions -cellZones -overwrite


# remove fluid fields from solid regions (important for post-processing)
for i in fluid
do
   rm -f 0*/$i/{Cp,K,rho}
done

for i in solid
do
   rm -f 0*/$i/{U,p,alpha1}
done


for i in fluid solid
do
   changeDictionary -region $i > log.changeDictionary.$i 2>&1
done

setFields -region fluid

#-- Run on single processor
#chtInterHeatFoam

# Decompose
runApplication decomposePar -allRegions

# Run
mpirun -np 2 chtInterHeatFoam -parallel > log 
#chtInterHeatFoam
# Reconstruct
runApplication reconstructPar -allRegions


echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll

# ----------------------------------------------------------------- end-of-file
